import { Montserrat } from 'next/font/google';

import { Footer, Header } from '@/components';

import './globals.css';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'LivisShop',
  description: 'Generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='en' data-theme='light'>
    <body className={`${inter.className}`}>
      <Header />
      {children}
      <Footer />
    </body>
  </html>
);

export default RootLayout;
